project:
  type: website
  output-dir: docs

website:
  title: "Alberto López Ortega"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - projects.qmd
     - resume.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css

editor: visual
